"""initial_schema

Revision ID: 2b4c854545f1
Revises: 
Create Date: 2026-10-01 20:10:43.921153

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4c854545f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campus_block', sa.String(length=100), nullable=True),
    sa.Column('enrolled_boarders', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostel_id', sa.String(length=36), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('daily_production_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostel_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_session', sa.String(length=50), nullable=True),
    sa.Column('prepared_qty', sa.Integer(), nullable=True),
    sa.Column('served_qty', sa.Integer(), nullable=True),
    sa.Column('surplus_qty', sa.Integer(), nullable=True),
    sa.Column('waste_qty', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_production_logs_date'), 'daily_production_logs', ['date'], unique=False)
    op.create_table('meal_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostel_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=50), nullable=False),
    sa.Column('menu', sa.Text(), nullable=False),
    sa.Column('time_window', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_schedules_date'), 'meal_schedules', ['date'], unique=False)
    op.create_table('ngo_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fssai_verified', sa.Boolean(), nullable=True),
    sa.Column('total_meals_rescued', sa.Integer(), nullable=True),
    sa.Column('people_served', sa.Integer(), nullable=True),
    sa.Column('co2_diverted_kg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('student_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roll_no', sa.String(length=100), nullable=False),
    sa.Column('hostel_id', sa.String(length=36), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('diet', sa.String(length=50), nullable=True),
    sa.Column('meals_booked', sa.Integer(), nullable=True),
    sa.Column('meals_saved', sa.Integer(), nullable=True),
    sa.Column('co2_avoided_kg', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_student_profiles_roll_no'), 'student_profiles', ['roll_no'], unique=True)
    op.create_table('surplus_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hostel_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meals', sa.Integer(), nullable=False),
    sa.Column('location_detail', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('pickup_deadline', sa.String(length=100), nullable=True),
    sa.Column('time_remaining', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('prep_time', sa.String(length=100), nullable=True),
    sa.Column('temp_celsius', sa.Integer(), nullable=True),
    sa.Column('storage_condition', sa.String(length=255), nullable=True),
    sa.Column('food_type', sa.String(length=255), nullable=True),
    sa.Column('fssai_safety_passed', sa.Boolean(), nullable=True),
    sa.Column('dietary', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('requested_by_ngo', sa.String(length=255), nullable=True),
    sa.Column('pickup_otp', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ngo_id', sa.String(length=36), nullable=False),
    sa.Column('food_title', sa.String(length=255), nullable=False),
    sa.Column('beneficiaries_served', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('proof_status', sa.String(length=50), nullable=True),
    sa.Column('co2_diverted_kg', sa.Float(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_session', sa.String(length=50), nullable=False),
    sa.Column('item_summary', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['meal_schedules.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_bookings_date'), 'meal_bookings', ['date'], unique=False)
    op.create_table('meal_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('meal_session', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surplus_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('surplus_id', sa.String(length=36), nullable=False),
    sa.Column('ngo_id', sa.String(length=36), nullable=False),
    sa.Column('volunteer_name', sa.String(length=255), nullable=False),
    sa.Column('vehicle', sa.String(length=255), nullable=True),
    sa.Column('eta', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=10), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngo_profiles.id'], ),
    sa.ForeignKeyConstraint(['surplus_id'], ['surplus_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surplus_requests')
    op.drop_table('meal_feedback')
    op.drop_index(op.f('ix_meal_bookings_date'), table_name='meal_bookings')
    op.drop_table('meal_bookings')
    op.drop_table('distribution_records')
    op.drop_table('surplus_listings')
    op.drop_index(op.f('ix_student_profiles_roll_no'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_table('ngo_profiles')
    op.drop_index(op.f('ix_meal_schedules_date'), table_name='meal_schedules')
    op.drop_table('meal_schedules')
    op.drop_index(op.f('ix_daily_production_logs_date'), table_name='daily_production_logs')
    op.drop_table('daily_production_logs')
    op.drop_table('admin_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('hostels')
    # ### end Alembic commands ###
